services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./scripts:/app/scripts:ro
      - ./docs/input:/app/docs/input:ro
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./docs/output:/app/docs/output
    working_dir: /app/scripts
    tty: true
